# Mostly copied from https://github.com/pre-commit/pre-commit-hooks/blob/main/.pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Update to the latest stable version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0  # Update to the latest stable version
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0  # Update to the latest stable version
    hooks:
    -   id: reorder-python-imports
        args: [--py38-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0  # Update to the latest stable version
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0  # Update to the latest stable version
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/hhatto/autopep8
    rev: v2.0.4  # Update to the latest stable version
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Update to the latest stable version
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0  # Update to the latest stable version
    hooks:
    -   id: mypy
-   repo: https://github.com/psf/black
    rev: 23.1.0  # Update to the latest stable version
    hooks:
    -   id: black
        language_version: python3
        args: ["--line-length", "120"]
        files: \.py$
